Details pop up window
Drew246/Portfolio-setup-and-mobile-first pull request #11
Opened 2023-08-01 23:20 UTC by Drew246

Added popup modal.

2023-08-01 23:49 UTC, AlphaNtihinduka requested changes
## Hello Team🙋‍♂️
Good job working on your popup. You have done the design to the best expectation and incredibly well. 👏  
 
You still need to implement a few on the project but you are almost there!!! 🚶: 

TO HIGHLIGHT:
- Popup disappears when (x) is clicked ✔️ 
- Correct use of map function ✔️ 
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-08-01 23:49 UTC, AlphaNtihinduka commented on app.js
> +   <div class="card-left-desk">
- [ ] As suggested in the ️[project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md), kindly try as much as possible to stick to the Figma original design. For this case, I suggest that you consider displaying all the contents of the popup card as seen in the Figma design ☺️. 
- [ ] In addition, I suggest that you reduce the blur effect to ensure that the background contents are blurry seen 👍.

Figma design 😎 
![image](https://github.com/Drew246/Portfolio-setup-and-mobile-first/assets/99394374/b14a990c-c442-40ff-af93-ddd9b8e3493a)

Your design 😎 
![image](https://github.com/Drew246/Portfolio-setup-and-mobile-first/assets/99394374/87ae9b73-c890-4bc5-b563-fc90da78f963)

2023-08-02 03:34 UTC, Shedrack-Sunday requested changes
Hello @Drew246        👋 

# CHANGES REQUIRED ♻️

Impressive work on the project so far👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with the JavaScript features for interaction✔️ 
    
 
  
# Required Changes  🌵  

- [ ] You've done well, However, kindly check some key point note I pointed out to meet the requirements before moving to the next project 👍 

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-08-02 03:34 UTC, Shedrack-Sunday commented on app.js
> +    .join('')}
- [ ] You did a great job 👏 . However, you intriduced a new bug, and still need to fix the chnages suggested by the last reviewer 👍 
- Firstly, your cancel button has been omitted.

### View:
![image](https://github.com/Drew246/Portfolio-setup-and-mobile-first/assets/50990925/671e3ecf-054c-4a10-b0d4-1031e8cf22b2)

### Figma design:
![image](https://github.com/Drew246/Portfolio-setup-and-mobile-first/assets/50990925/145b25a3-eb1a-42c2-a58c-009198accb83)

- [ ] Secondly, just as the last reveiver pointed out, kindly adjust your popup. The buttom part should be visible on the screen, and fixed just as it is on figma. You can make reference  the materils for this week's for that 👍 

### Figma:
![image](https://github.com/Drew246/Portfolio-setup-and-mobile-first/assets/50990925/60385406-7d77-4883-9f36-995e57cb7535)

### Your design:
![image](https://github.com/Drew246/Portfolio-setup-and-mobile-first/assets/50990925/0a882244-d392-407d-bd4c-410046921610)

2023-08-02 03:47 UTC, Drew246 commented
Hi, I am not sure if something went wrong but I am not seeing the bug you
are talking about. My close button was visible when I checked. also, the
bottom of the modal is visible.
Can yo take another look?

On Tue, Aug 1, 2023 at 11:34 PM Shedrack Sunday ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hello @Drew246 <https://github.com/Drew246> 👋
> CHANGES REQUIRED ♻️
>
> Impressive work on the project so far👏
> You've done extremely well so far in this project, However, there are some
> adjustments you need to make to move to the next project. 💯
>
>
> <https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif>
> Highlights
>
>    - Good use of GitHub features ✔️
>    - Nice work with the JavaScript features for interaction✔️
>
> Required Changes 🌵
>
>    - You've done well, However, kindly check some key point note I
>    pointed out to meet the requirements before moving to the next project 👍
>
> _Check the comments for a detailed review
> Optional suggestions
>
> Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing really improves your application.
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.
>
> As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.
> ------------------------------
>
> In app.js
> <https://github.com/Drew246/Portfolio-setup-and-mobile-first/pull/11#discussion_r1281349969>
> :
>
> > +if (portfolio) {
> +  for (let i = 0; i < portfolioItemsDetail.length; i += 1) {
> +    const div = document.createElement('div');
> +    div.classList.add('card');
> +    div.setAttribute('id', `${i}`);
> +    div.innerHTML = `
> +   <div class="card-left-mobile">
> +   <img src="${portfolioItemsDetail[i].images}" alt="snap-card">
> +   </div>
> +   <div class="card-right">
> +     <h2>${portfolioItemsDetail[i].name}</h2>
> +     <ul class="cano">
> +       <li>${portfolioItemsDetail[i].title}<i class="fa fa-circle"></i></li>
> +       <li>${portfolioItemsDetail[i].stack}<i class="fa fa-circle"></i></li>
> +       <li>2015</li>
> +     </ul>
> +     <p>${portfolioItemsDetail[i].text}</p>
> +     <ul class="lang">
> +       ${portfolioItemsDetail[i].workStack
> +    .map((stack) => `<li>${stack}</li>`)
> +    .join('')}
>
>
>    - You did a great job 👏 . However, you intriduced a new bug, and
>    still need to fix the chnages suggested by the last reviewer 👍
>    - Firstly, your cancel button has been omitted.
>
> View:
>
> [image: image]
> <https://user-images.githubusercontent.com/50990925/257692709-671e3ecf-054c-4a10-b0d4-1031e8cf22b2.png>
> Figma design:
>
> [image: image]
> <https://user-images.githubusercontent.com/50990925/257692786-145b25a3-eb1a-42c2-a58c-009198accb83.png>
>
>    - Secondly, just as the last reveiver pointed out, kindly adjust your
>    popup. The buttom part should be visible on the screen, and fixed just as
>    it is on figma. You can make reference the materils for this week's for
>    that 👍
>
> Figma:
>
> [image: image]
> <https://user-images.githubusercontent.com/50990925/257693380-60385406-7d77-4883-9f36-995e57cb7535.png>
> Your design:
>
> [image: image]
> <https://user-images.githubusercontent.com/50990925/257693536-0a882244-d392-407d-bd4c-410046921610.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Drew246/Portfolio-setup-and-mobile-first/pull/11#pullrequestreview-1558130260>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATMBYTSU3DD2O5BTIAYKB6DXTHDGDANCNFSM6AAAAAA3AOHUCY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2023-08-02 04:02 UTC, Shedrack-Sunday commented
Hello @Drew246, this is the view I get from cloning your project locally. Please confirm the changes see are pushed to the current branch

2023-08-02 04:03 UTC, Drew246 commented
I pushed. Are you on the Details -popup branch?

On Wed, Aug 2, 2023, 12:02 AM Shedrack Sunday ***@***.***>
wrote:

> Hello @Drew246 <https://github.com/Drew246>, this is the view I get from
> cloning your project locally. Please confirm the changes see are pushed to
> the current branch
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Drew246/Portfolio-setup-and-mobile-first/pull/11#issuecomment-1661455526>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATMBYTSZIK7SVEHY3DP5FNLXTHGMPANCNFSM6AAAAAA3AOHUCY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-02 04:07 UTC, Shedrack-Sunday commented
Yes, I used the branch in which you created the PR. Please snap the current popup that you have on that branch

2023-08-02 04:27 UTC, Drew246 commented
The current popup is already there. Something is wrong. Should I create a
new pull request? Can you please kindly verify the branch once more? I
double checked and everything is fine on my end.

On Wed, Aug 2, 2023 at 12:07 AM Shedrack Sunday ***@***.***>
wrote:

> Yes, I used the branch in which you created the PR. Please snap the
> current popup that you have on that branch
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Drew246/Portfolio-setup-and-mobile-first/pull/11#issuecomment-1661459440>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATMBYTRNGLHAKVJLKJAG53TXTHHBLANCNFSM6AAAAAA3AOHUCY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-02 04:52 UTC, Drew246 commented
I have to sleep now. But i would like to zoom call you in a few hours. I do
not want to waste one of my reviews.

On Wed, Aug 2, 2023 at 12:07 AM Shedrack Sunday ***@***.***>
wrote:

> Yes, I used the branch in which you created the PR. Please snap the
> current popup that you have on that branch
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Drew246/Portfolio-setup-and-mobile-first/pull/11#issuecomment-1661459440>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATMBYTRNGLHAKVJLKJAG53TXTHHBLANCNFSM6AAAAAA3AOHUCY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-02 14:06 UTC, V-Blaze approved these changes
Hi @Drew246  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Pop-up works as expected 💯
-  Project section generated dynamically👍
-  Good communication with previous reviewers 🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 14:55 UTC, merged